version: 0.2

phases:
  pre_build:
    commands:
      - echo "Fase 1: Preparando entorno"
  build:
    commands:
      - echo "Fase 2: Construyendo imagen Docker"
      - docker build -t flask-app ./app
      - echo "Build completado con exito"
  post_build:
    commands:
      - echo "Fase 3: Pipeline finalizada correctamente"

artifacts:
  files:
    - '**/*'
